{% set name = "rucio-clients" %}
{% set version = "37.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6c4b29ead0b971bb08c9d3304333a6046ab009538af0c3b960de67416909e83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=8.1.7
    - dogpile.cache >=1.2.2
    - jsonschema >=4.23.0
    - packaging >=24.2
    - requests >=2.32.3
    - rich >=13.9.4
    - tabulate >=0.9.0
    - typing_extensions >=4.12.2
    - urllib3 >=2.3.0

test:
  imports:
    - rucio
    - rucio.client
  # disable pip check for now, the conda recipe is fine but the pypi package contains wrong dependencies
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
    - maxnoe
