{% set name = "rucio-clients" %}
{% set version = "33.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rucio-clients-{{ version }}.tar.gz
  sha256: 307480b57feefe827e1fdab64daf1a95fea2f3b3ea1f12913a1d331af695f76f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - dogpile.cache ~=1.2.2
    - jsonschema ~=4.18.4
    - requests >=2.25.1,<=2.31.0
    - tabulate ~=0.9.0
    - urllib3 ~=1.26.15

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
