{% set name = "rucio-clients" %}
{% set version = "39.0.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a83632897cfc2cc9052848b1b795fb71b2cf8d0a7920a6cff1f7367874bac72a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=8.1.8
    - dogpile.cache >=1.2.2
    - jsonschema >=4.25.1
    - packaging >=25.0
    - requests >=2.32.5
    - rich >=14.2.0
    - tabulate >=0.9.0
    - typing_extensions >=4.15.0
    - urllib3 >=2.6.3

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
    - maxnoe
