{% set name = "rucio-clients" %}
{% set version = "41.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 02af4aa25f1d48a2ec54cf92aa96225ef95a93807f930aa37e0e2607d11b1070

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - dogpile.cache
    - jsonschema
    - packaging
    - requests
    - rich
    - tabulate
    - typing_extensions
    - urllib3

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
    - maxnoe
