{% set name = "rucio-clients" %}
{% set version = "1.30.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rucio-clients-{{ version }}.tar.gz
  sha256: 93924bdc6bfaef77b85d033676b9dcb08db7e2c0758c6a3b2d0b11f426524530

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dogpile.cache >=1.1.2,<=1.1.5
    - jsonschema ~=3.2.0
    - python >=3.6
    - requests >=2.20.0,<=2.27.1
    - tabulate ~=0.8.0
    - urllib3 >=1.24.2,<=1.26.8

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
