{% set name = "rucio-clients" %}
{% set version = "36.0.0.post2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 48ac2e3217aac9aaa70133cbfff991560bbeb162165bcf3dd3425967c8a2f816

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 3.9
    - setuptools
  run:
    - python >=3.9
    - dogpile.cache >=1.2.2
    - jsonschema >=4.23.0
    - packaging >=24.1
    - requests >=2.32.3
    - rich >=13.7.1
    - tabulate >=0.9.0
    - urllib3 >=1.26.19

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip
    - python 3.9

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
