{% set name = "rucio-clients" %}
{% set version = "36.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3a85092e08a4bc17ac23803d390b34471166521fa48f5735b7f1c4560f4743bc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - dogpile.cache >=1.2.2
    - jsonschema >=4.23.0
    - packaging >=24.1
    - paramiko >=3.4.0
    - requests >=2.32.3
    - rich >=13.7.1
    - tabulate >=0.9.0
    - urllib3 >=1.26.19

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
