{% set name = "rucio-clients" %}
{% set version = "37.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c37a0570c54574f06926679967031e9fc418e18c51094631890b83ed4007554c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - dogpile.cache >=1.2.2
    - jsonschema >=4.23.0
    - packaging >=24.2
    - requests >=2.32.3
    - rich >=13.9.4
    - tabulate >=0.9.0
    - urllib3 >=2.3.0
    - click >=8.1.7

test:
  imports:
    - rucio
    - rucio.client
  # disable pip check for now, the conda recipe is fine but the pypi package contains wrong dependencies
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
    - maxnoe
